### ISSUE TITLE
Cannot read properties of undefined (reading 'prototype') in java.time

### ISSUE THREAD

**Issue by qazwsxpawel** [juxt/tick#171]
Hello 👋 

I'm seeing: 

```
TypeError: Cannot read properties of undefined (reading 'prototype')
    at eval (time.cljs:29:3)
    at eval (<anonymous>)
    at goog.globalEval (app.js:472:11)
    at env.evalLoad (app.js:1534:12)
    at app.js:2113:12
```
The ns is `java.time`, and the line it's pointing at is: 

```
(extend-protocol IComparable
...
  OffsetTime (-compare [x y] (.compareTo ^js/Object x y))
...)
```

This is in a cljs app, built with shadow for the browser — some key deps are: 
```
thheller/shadow-cljs                             2.19.3
org.clojure/clojure                              1.11.1
org.clojure/clojurescript                        1.11.57
com.google.javascript/closure-compiler-unshaded  v20220601
tick/tick                                        0.5.0-RC6
```
This is happening on "app initialisation"

Please let me know if that makes sense or if you need more info/context.

Cheers!

**Comment by henryw374** [comment]
can you see what version of js-joda/core you have in package.json. should be 3.2.0 as per https://github.com/henryw374/cljs.java-time/blob/master/src/deps.cljs

**Comment by henryw374** [comment]
welcome!
