### ISSUE TITLE
Tick breaks clj -Stree

### ISSUE THREAD

**Issue by eerohele** [juxt/tick#25]
Repro:

```bash
$ echo '{:deps {tick {:mvn/version "0.4.7-alpha"}}}' > deps.edn
$ clj -Stree
```

Error:

```
Error printing tree. Invalid token: /cljs.java-time
java.lang.RuntimeException: Invalid token: /cljs.java-time
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.EdnReader.interpretToken(EdnReader.java:285)
	at clojure.lang.EdnReader.read(EdnReader.java:171)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:766)
	at clojure.lang.EdnReader$SetReader.invoke(EdnReader.java:691)
	at clojure.lang.EdnReader$DispatchReader.invoke(EdnReader.java:554)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:757)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:680)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:757)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:680)
	at clojure.lang.EdnReader.read(EdnReader.java:145)
	at clojure.lang.EdnReader.read(EdnReader.java:111)
	at clojure.edn$read.invokeStatic(edn.clj:35)
	at clojure.edn$read.invoke(edn.clj:14)
	at clojure.tools.deps.alpha.util.io$slurp_edn.invokeStatic(io.clj:29)
	at clojure.tools.deps.alpha.util.io$slurp_edn.invoke(io.clj:22)
	at clojure.tools.deps.alpha.script.print_tree$run.invokeStatic(print_tree.clj:23)
	at clojure.tools.deps.alpha.script.print_tree$run.invoke(print_tree.clj:20)
	at clojure.tools.deps.alpha.script.print_tree$_main.invokeStatic(print_tree.clj:39)
	at clojure.tools.deps.alpha.script.print_tree$_main.doInvoke(print_tree.clj:26)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.main$main_opt.invokeStatic(main.clj:317)
	at clojure.main$main_opt.invoke(main.clj:313)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
```

**Comment by henryw374** [comment]
fyi upstream prob https://dev.clojure.org/jira/browse/TDEPS-107
