### ISSUE TITLE
js-joda-timezone does not get pulled in unless it is explicitly required by caller

### ISSUE THREAD

**Issue by antonmos** [juxt/tick#61]
```
Cannot read property ‘length’ of undefined: 2019-08-30T17:00-00:00[US/Eastern], at index: 0
-------
Caused by: TypeError: Cannot read property ‘length’ of undefined
   at Function.createTreeMap (/Users/amostovoy/dev/gr-mismo/target/doo/out/cljsjs/js-joda/development/js-joda.inc.js:5266:62)
   at ZoneIdPrinterParser.parse (/Users/amostovoy/dev/gr-mismo/target/doo/out/cljsjs/js-joda/development/js-joda.inc.js:5213:41)
```

This happened because it was using ZoneRulesProvider which has getAvailableZoneIds returning [].

Once we required `[cljsjs.js-joda-timezone]` in our namespace, we saw that js-joda-timezone got pulled into the cljsjs folder and it worked.

cc @ckirkendall

**Comment by henryw374** [comment]
Hopefully this helps: https://github.com/juxt/tick/blob/master/docs/cljs.adoc

**Comment by antonmos** [comment]
ha, i am pretty sure i read that section and definitely the one below it, but somehow it didnt ring a bell for me.  Thanks!
