### ISSUE TITLE
Addition of instant and period of months unit fails

### ISSUE THREAD

**Issue by jaimesangcap** [juxt/tick#98]
**Version**: tick {:mvn/version "0.4.24-alpha"}

When using below code in clojurescript, it throws an error
```
(ns limeray.web.component
  (:require
    [tick.alpha.api :as t]))

(t/+ (t/instant) (t/new-period 2 :months))
```

**ERROR**
```
UnsupportedTemporalTypeException: Unsupported unit: Months
    at Instant._proto.plus2 (http://localhost:9000//cljs-runtime/module$node_modules$$js_joda$core$dist$js_joda.js:456:35)
    at Instant._proto.plus (http://localhost:9000//cljs-runtime/module$node_modules$$js_joda$core$dist$js_joda.js:454:94)
    at Period._proto.addTo (http://localhost:9000//cljs-runtime/module$node_modules$$js_joda$core$dist$js_joda.js:82:162)
    at Instant._proto.plus1 (http://localhost:9000//cljs-runtime/module$node_modules$$js_joda$core$dist$js_joda.js:454:190)
    at Instant._proto.plus (http://localhost:9000//cljs-runtime/module$node_modules$$js_joda$core$dist$js_joda.js:454:75)
    at eval (http://localhost:9000//cljs-runtime/tick.core.js:3637:10)
    at tick$core$ITimeArithmetic$_PLUS_$dyn_56871 (http://localhost:9000//cljs-runtime/tick.core.js:3561:126)
    at Object.tick$core$_PLUS_ [as _PLUS_] (http://localhost:9000//cljs-runtime/tick.core.js:3578:8)
    at eval (http://localhost:9000//cljs-runtime/tick.alpha.api.js:523:18)
    at eval (http://localhost:9000//cljs-runtime/cljs.core.js:5437:98)
```

However adding `:days` unit works. Why is that?

```
$ (t/+ (t/instant) (t/new-period 2 :days))
=> #time/instant"2020-08-25T11:01:46.468Z"
```

**Comment by henryw374** [comment]
Hi. 

This issue you raise is so common it prompted me to add https://github.com/juxt/tick/blob/master/CONTRIBUTING.adoc . Hopefully that clears things up?

**Comment by jaimesangcap** [comment]
Thank you for the reference, it was very helpful.
